package com.pathfinder.graph.exception;

/**
 * Exception to be called if an edge cannot be found in a graph
 */
public class EdgeNotInGraphException extends GraphException{

	/**
	 * Autogenerated serial ID
	 */
	private static final long serialVersionUID = -172039662673862504L;

	//default parameterless constructor
	public EdgeNotInGraphException() {}
		
	//Standard message constructor
	public EdgeNotInGraphException(String msg){
		super(msg);
	}
}

