package com.pathfinder.graph.exception;

/**
 * Generic parent exception for any graph-related exception
 */
public class GraphException extends Exception {
	
	/**
	 * Autogenerated serial ID
	 */
	private static final long serialVersionUID = 815813777481063621L;

	//default parameterless exception
	public GraphException(){}
	
	public GraphException(String msg){
		super(msg);
	}
}
